config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/landing', to: 'pages#landing', as: :landing
  get '/about', to: 'pages#about', as: :about
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :communities, only: [:create]

  resources :profiles, only: [:show, :index, :edit, :update, :destroy] do
    resources :user_images, only: [:show, :destroy, :update, :edit]
    resources :matches, only: [:create]
    resources :dislikes, only: [:create]
    get '/onboard', to: 'profiles#onboard'
  end

  mount ActionCable.server => "/cable"
end

app/controllers/profiles_controller.rb
require 'open-uri'
require 'json'

class ProfilesController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index

  def index
    query = <<-SQL
      SELECT * FROM users u
      WHERE id NOT IN
      (
        SELECT second_user_id FROM matches WHERE first_user_id = :current_user_id
        UNION
        SELECT first_user_id FROM matches WHERE second_user_id = :current_user_id AND mutual = TRUE
        UNION
        SELECT id FROM users WHERE gender NOT IN (:gender_preferences)
        UNION
        SELECT second_user_id FROM dislikes WHERE first_user_id = :current_user_id
        UNION
        SELECT id FROM users WHERE community_id != :current_user_community_id
      )
      AND u.id != :current_user_id
    SQL

    users_allowed = User.find_by_sql([ query, { current_user_id: current_user.id, gender_preferences: current_user.gender_preferences, current_user_community_id: current_user.community.id }])
    number = Date.today.to_time.to_i + current_user.id.to_i
    @users = users_allowed #.sample(12, random: Random.new(number))
    ActiveRecord::Associations::Preloader.new.preload(@users, :user_images)
    @user = current_user
  end

  def show
    @user = User.includes(:user_images).find(params[:id])
    authorize @user
  end

  def edit
    @user = User.includes(:user_images).find(params[:id])
    @user_images = @user.user_images.order({id: :asc})
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to edit_profile_path(@user) }
        format.js
      end
    else
      puts "you fucked up"
    end
  end

  def onboard
    @user = User.find(params[:profile_id])
    authorize @user
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:gender, :first_name, :last_name, :course, :college, :what_im_into, :looking_for, {:gender_preferences => []}, user_images: [:id, :user_id, :photo])
  end

end

app/views/profiles/edit.html.erb
<% content_for(:title_tag) do %>
  Edit Your Profile - Meteor
<% end %>

<div class="edit-box-for-cards">
  <div>
    <div class="swiper-container swiper-edit">
        <div class="swiper-wrapper">
        <% @user_images.each do |photo| %>
            <div class="swiper-slide avatar-photo" style="background-image: url(<%= photo.small_url %>)">
             <%= link_to "", profile_user_image_path(@user,photo), class: "link-image-edit" %> </div>
        <% end %>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-scrollbar"></div>
    </div>
  </div>
</div>

<div class="container edit-attributes">

  <div class="single-attribute">
    <h4 class="attribute-title">Course</h4>
    <div class="attribute-body">
      <p>
        <%= @user.course %>
      </p>
      <div data-toggle="modal" data-target="#courseModal" data-content="courseModal">
        <a class="edit-button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> edit</a>
      </div>
    </div>
  </div>

  <div class="single-attribute">
    <h4 class="attribute-title">College</h4>
    <div class="attribute-body">
      <p>
        <%= @user.college %>
      </p>
      <div data-toggle="modal" data-target="#collegeModal" data-content="collegeModal">
        <a class="edit-button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> edit</a>
      </div>
    </div>
  </div>

  <div class="single-attribute">
    <h4 class="attribute-title">What I'm into</h4>
    <div class="attribute-body">
      <p>
        <%= @user.what_im_into %>
      </p>
      <div data-toggle="modal" data-target="#what_im_intoModal" data-content="what_im_intoModal">
        <a class="edit-button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> edit</a>
      </div>
    </div>
  </div>

  <div class="single-attribute">
    <h4 class="attribute-title">What I'm looking for</h4>
    <div class="attribute-body">
      <p>
        <%= @user.looking_for %>
      </p>
      <div data-toggle="modal" data-target="#looking_forModal" data-content="looking_forModal">
        <a class="edit-button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> edit</a>
      </div>
    </div>
  </div>

</div>


<div class="text-center remove-profile">
  <%= link_to "Remove your profile", profile_path(@user), data: { confirm: "Are you sure?" }, method: :delete %>
</div>

<!-- Here be modals -->
<div class="modal fade modal-edit" id="courseModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= simple_form_for @user, :url => profile_path(@user), :method => :patch do |f| %>
        <%= f.input :course, label: "Course", input_html: { rows: '10', class: "input-no-resize"} %>
      </div>
      <div class="modal-footer footer-flexbox">
        <%= f.button :submit, "Save", class: 'btn btn-success show-navbar' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade modal-edit" id="collegeModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= simple_form_for @user, :url => profile_path, :method => :patch do |f| %>
        <%= f.input :college, label: "College", input_html: { rows: '5', class: "input-no-resize"} %>
      </div>
      <div class="modal-footer footer-flexbox">
        <%= f.button :submit, "Save", class: 'btn btn-success show-navbar' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade modal-edit" id="looking_forModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= simple_form_for @user, :url => profile_path(@user), :method => :patch do |f| %>
        <%= f.input :looking_for, label: "What I'm looking for", input_html: { rows: '10', class: "input-no-resize"} %>
      </div>
      <div class="modal-footer footer-flexbox">
        <%= f.button :submit, "Save", class: 'btn btn-success show-navbar' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade modal-edit" id="what_im_intoModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= simple_form_for @user, :url => profile_path(@user), :method => :patch do |f| %>
        <%= f.input :what_im_into, label: "What I'm into", input_html: { rows: '10', class: "input-no-resize"} %>
      </div>
      <div class="modal-footer footer-flexbox">
        <%= f.button :submit, "Save", class: 'btn btn-success show-navbar' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<% content_for(:title_tag) do %>
  Profiles List - Meteor
<% end %>

<div class="not-for-mobile-container">
<!--   <h2 class="profiles-title text-center hidden-xs">Your top profiles for today</h2>
 -->
  <div class="profile-cards">
    <div class="swiper-container swiper-all-cards">
        <div class="swiper-wrapper">
          <% @users.each do |user| %>
            <div class="swiper-slide"><%= render "shared/card", user: user %></div>
          <% end %>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-all-cards"></div>
    </div>
  </div>

</div>

app/views/profiles/onboard.html.erb
<% content_for(:title_tag) do %>
  Your Profile Onboarding - Meteor
<% end %>

<!-- <div class="onboard-wrapper"> -->
  <!-- Slider main container -->
  <div class="swiper-container swiper-onboard">
      <!-- Additional required wrapper -->
      <div class="swiper-wrapper">
          <!-- Slides -->
          <div class="swiper-slide">
            <div class="card-container">
              <div class="card onboard-card">
                  <div class="card-body">
                  <%= simple_form_for @user, remote: true, :url => profile_path(@user), :method => :patch do |f| %>
                  <%= f.input :course, label: "What are you studying?", placeholder: 'Studying philosophy at Oxford' %>
                  </div>
                  <div class="card-footer">
                    <%= f.button :submit, "Next", class: 'btn btn-primary btn-block' %>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="card-container">
              <div class="card onboard-card">
                  <div class="card-body">
                  <%= simple_form_for @user, remote: true, :url => profile_path(@user), :method => :patch do |f| %>
                  <%= f.input :what_im_into, label: "Add a Bio", placeholder: '' %>
                  </div>
                  <div class="card-footer">
                    <%= f.button :submit, "Next", class: 'btn btn-primary btn-block' %>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>

          <div class="swiper-slide">
            <div class="card-container">
              <div class="card onboard-card">
                  <div class="card-body">
                    <%= simple_form_for @user, :url => profile_path(@user), :method => :patch do |f| %>
                    <%
                      genders = [
                        [ 'male', 'Men' ],
                        [ 'female', 'Women' ],
                        [ 'non_binary', 'Other' ]
                      ]
                    %>
                    <%= f.input :gender_preferences, label: "I'm interested in", as: :check_boxes,
                          collection: genders,
                          value_method: :first,
                          label_method: :last %>
                  </div>
                  <div class="card-footer">
                    <%= f.button :submit, "Done", class: 'btn btn-primary btn-block' %>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>

      </div>

      <div class="swiper-button-next onboard-next hide"></div>
      <!-- If we need pagination -->
      <div class="swiper-pagination"></div>

  </div>
<!-- </div> -->

app/views/profiles/show.html.erb
<% content_for(:title_tag) do %>
  <%= "#{@user.first_name}'s Profile" %> - Meteor
<% end %>

<div class="hidden-md hidden-lg">
  <div class="swiper-container swiper-show-card">
      <!-- Additional required wrapper -->
      <div class="swiper-wrapper">
          <!-- Slides -->
          <!-- test slide below -->
          <% images = @user.user_images.order({id: :asc}) %>
          <div class="swiper-slide banner-photo-show" style="background-image: url(<%= image_path (images.first&.medium_url || @user.facebook_picture_url) %>);" ></div>
          <!-- end of test slide -->
          <% images.drop(1).each do |image| %>
            <div class="swiper-slide banner-photo-show" style="background-image: url( <%= image_path image.medium_url %>);" ></div>
          <% end %>
      </div>
      <!-- If we need pagination -->
      <div class="swiper-pagination swiper-pagination-white swiper-show-card"></div>

      <!-- If we need navigation buttons -->
      <!-- <div class="swiper-button-prev swiper-show-card"></div> -->
      <!-- <div class="swiper-button-next swiper-show-card"></div> -->

      <!-- If we need scrollbar -->
  </div>
</div>


<div class="hidden-sm hidden-xs">
  <!-- TODO lightbox2 gallery -->
  <div class="profile-gallery">
    <% @user.user_images.each_with_index do |photo, n| %>

      <a href="<%= image_path photo.url %>" data-lightbox="image-profile" data-title="My caption">
        <div class="profile-gallery-img" style="background-image: url(<%= image_path photo.url %>);">
        </div>
      </a>
    <% end %>
  </div>
</div>

<div class="container profile-content">

  <div class="profile-titles">
    <div class="user-title">
      <p><%= @user.first_name %>, <%= @user.age %><p>
<!--       <p><%= @user.subject %></p> -->
      <div class="user-course-col">
        <% if @user.course %>
          <p><%= @user.course %>, <%= @user.college %></p>
        <% end %>
      </div>
    </div>
    <div class="match-percentage">
    </div>
  </div>


  <div class="profile-attributes">
    <h3>What I'm into</h3>
    <p>
    <%= @user.what_im_into %>
<!--       Currently studying History of Art, and looking for a serious relationship. My interests include History, Art, and relationships.

      I like coming up with big ideas and then bring them to life. Love good music. I have a passion for architecture. Always eager to learn new things.

      Free to chat and meet up on campus at any time! -->
    </p>
  </div>

  <div class="profile-attributes">
    <h3>What I'm looking for</h3>
    <p>
    <%= @user.looking_for %>
    </p>
  </div>

</div>

<% if current_user.likes_user(@user) == [] %>

  <div class="buttons">

    <%=link_to profile_dislikes_path(@user), method: :post do %>
      <div class="no match-choice-btn">
        <%= image_tag("no-btn.png") %>
      </div>
    <% end %>

    <%= link_to profile_matches_path(@user), method: :post do %>
      <div class="like match-choice-btn">
        <%= image_tag("like-btn.png") %>
      </div>
    <% end %>

  </div>
<% end %>


<% content_for(:after_js) do %>

<% end %>

app/views/profiles/update.js.erb
const nextBtn = document.querySelector(".onboard-next");
nextBtn.click();