config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/landing', to: 'pages#landing', as: :landing
  get '/about', to: 'pages#about', as: :about
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :communities, only: [:create]

  resources :profiles, only: [:show, :index, :edit, :update, :destroy] do
    resources :user_images, only: [:show, :destroy, :update, :edit]
    resources :matches, only: [:create]
    resources :dislikes, only: [:create]
    get '/onboard', to: 'profiles#onboard'
  end

  mount ActionCable.server => "/cable"
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :match
  has_many :messages, dependent: :destroy

  def name
    id
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
  end

  def show
    @conversation = Conversation.includes(messages: { user: :user_images }).find(params[:id])
    authorize @conversation
    @conversation.update(last_opened_id: current_user.id)
  end

 def index
    # @conversation = Conversation.includes(messages: :user).find(params[:id])
    conversations = policy_scope(Conversation)
    @user = current_user
    if conversations == []

      redirect_to profiles_path, alert: 'You have to match with someone to start a conversation!'
    else
      @started = []
      @unstarted = []
      conversations.delete(nil)
      conversations.each do |convo|
          if convo.messages == []
            @unstarted << convo
          else
            @started << convo
          end
      end
    end
  end

  def conversation_params
    params.require(:conversation).permit(:last_opened_id)
  end
end

app/views/conversations/_conversations.html.erb
<% conversations.sort_by { |conv| conv.messages.last.created_at }.reverse.each do |convo| %>
  <div class="single-message">
    <div class="avatar-top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path convo.match.other_user(current_user).user_images.first&.small_url || convo.match.other_user(current_user).facebook_picture_url %>);">
    </div>
    <div class="messagess-body">
      <p><strong><h5> <%= convo.match.other_user(current_user).first_name %> </h5></strong></p>

      <div class="convo-text">
      <%= truncate(convo.messages.last.content, :length => 30) %>
      </div>

    </div>
    <%= link_to "", conversation_path(convo), class: "message-link-new" %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<% content_for(:title_tag) do %>
  Your Conversations - Meteor
<% end %>

<div class="wrapper1">
  <div class="top-scroll">
    <% @unstarted.each do |convo| %>

      <div class="avatar-top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path convo.match.other_user(current_user).user_images.first&.small_url || convo.match.other_user(current_user).facebook_picture_url %>);">
      <%= link_to "", conversation_path(convo), class: "avatar-link" %>
      </div>
    <% end %>
  </div>
</div>

<%# if @started != [] %>
  <%# @started.each do |conversation| %>

    <%# if (!conversation.messages.last.from?(current_user)) && conversation.last_opened_id != current_user.id %>
      <%# variable_to_know_if_unread = 'unread' %>
    <%# elsif (!conversation.messages.last.from?(current_user)) && conversation.last_opened_id == current_user.id %>
      <%# variable_to_know_if_unread = '' %>
    <%# else  %>
      <%# variable_to_know_if_unread = '' %>
    <%# end %>

  <div class="messages-box">

      <%= render 'conversations', conversations: @started %>

  </div>

  <%# end %>
<%# end %>



<%= content_for(:after_js) do %>
  <script>
    App['user_<%= @user.id %>'] = App.cable.subscriptions.create(
      { channel: 'UsersChannel', user_id: <%= @user.id %> },
      {
        received: (data) => {
          $.getScript("<%= conversations_path %>");
        }
      });
  </script>
<% end %>




<!-- <script>
  setTimeout(window.location.reload(), 5000);
</script>
 -->

app/views/conversations/index.js.erb
$('.messages-box').html("<%= j render 'conversations', conversations: @started %>");

app/views/conversations/show.html.erb
<% content_for(:title_tag) do %>
  Conversation - Meteor
<% end %>

<!-- <div class="chat-interface kill-padding kill-margin"> -->
  <!-- <div class="row"> -->
<!--     <div class="col-sm-6 col-sm-4">
 -->      <div class="chat-header">
        <%= link_to conversations_path do %>
          <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <% end %>
        <div class="match-name">
          <h4><%= @conversation.match.other_user(current_user).first_name %></h4>
        </div>
      </div>
      <div class="messages">
        <% @conversation.messages.each do |message| %>
          <%= render "shared/message", message: message, user_is_messages_author: (message.user == current_user) %>
        <% end %>
      </div>
      <div class="bottom-message">
        <div id="create-message">
          <form novalidate="novalidate" class="simple_form new_message" id="new_message" action="/conversations/<%= @conversation.id %>/messages" accept-charset="UTF-8" data-remote="true" method="post">
          <input name="utf8" type="hidden" value="✓">
          <div class="form-group text required message_content"><textarea class="form-control text required" name="message[content]" id="message_content"></textarea></div>
          <div class="send-btn-chat">
            <input type="submit" name="commit" value="send" data-disable-with="Send">
          </div>
          </form>
        </div>
      </div>

<%= content_for(:after_js) do %>
  <script>
    scrollLastMessageIntoView();
    App['conversation_<%= @conversation.id %>'] = App.cable.subscriptions.create(
      { channel: 'ConversationsChannel', conversation_id: <%= @conversation.id %> },
      {
        received: (data) => {
        if (data.current_user_id !== <%= current_user.id %>) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
          scrollLastMessageIntoView();
        }}})
  </script>
<% end %>