config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/landing', to: 'pages#landing', as: :landing
  get '/about', to: 'pages#about', as: :about
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :communities, only: [:create]

  resources :profiles, only: [:show, :index, :edit, :update, :destroy] do
    resources :user_images, only: [:show, :destroy, :update, :edit]
    resources :matches, only: [:create]
    resources :dislikes, only: [:create]
    get '/onboard', to: 'profiles#onboard'
  end

  mount ActionCable.server => "/cable"
end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user

  def url
    facebook_images.first["source"]
    # return JSON.parse(open(base_url).read)["images"].first["source"] # first picks largest size availble
  end

  # def medium_url
  #   base_url = "https://graph.facebook.com/#{self.photo}?fields=images&access_token=#{self.user.token}" # passed in the id and foreign key
  #   third_image = JSON.parse(open(base_url).read)["images"].third # third picks medium size if availble
  #   if third_image
  #     return third_image["source"]
  #   else
  #     # if we can't find a medium size image we return the full size
  #     self.url
  #   end
  # end

  def small_url
    facebook_images.last["source"]
  end

  def medium_url
    images = facebook_images
    if images.third.nil?
      images.first["source"]
    else
      images.third["source"]
    end
  end

  private

  def facebook_images
    Cache.instance.get(:facebook_images, user.id, fb_photo_id) do
      base_url = "https://graph.facebook.com/#{fb_photo_id}?fields=images&access_token=#{user.token}" # passed in the id and foreign key
      JSON.parse(open(base_url).read)["images"]
    end
  end
end

app/controllers/user_images_controller.rb
class UserImagesController < ApplicationController
  def edit
    @user = User.find(params[:profile_id])
    @photo = @user.user_images.find(params[:id])
    authorize @user, :edit_image?
    authorize @photo
  end

  def update
    @user = User.find(params[:profile_id])
    @photo = UserImage.find(params[:id])
    authorize @photo
    authorize @user
    if @photo.update(photo_params)
      redirect_to edit_profile_path(@user)
    else
      render :edit, alert: "Something went wrong"
    end
  end

  def show
    @user = User.find(params[:profile_id])
    @photo = @user.user_images.find(params[:id])
    authorize @photo
  end

  def destroy
    @photo = UserImage.find(params[:id])
    authorize @photo
    if @photo.delete
      redirect_to edit_profile_path(current_user)
    else
      render :show
    end
  end

  private

  def photo_params
    params.require(:fb_image).permit(:fb_photo_id)
  end

end

app/views/user_images/edit.html.erb
<% content_for(:title_tag) do %>
  Edit Your Photos - Meteor
<% end %>

<div class="container">
  <div class="row">
    <% @user.all_fb_photos_page.each do |hash| %>
      <div class="col-xs-4 kill-padding ">
        <%= link_to profile_user_image_path(profile_id: @user.id, id: @photo.id, fb_image: hash), :method => :patch do%>
          <div class="tagged-photo" style="background-image: url(<%= hash[:url] %>);"></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_images/show.html.erb
<% content_for(:title_tag) do %>
  Your Photos - Meteor
<% end %>

<div class="wrapper-black">
  <div class="wrapper-black-empty"></div>
  <div class="edit-photo-image" style="background-image: url( <%= @photo.url %> )">
  </div>
    <div class="edit-box-image" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <div class="edit-dropdown-content">
        <div class="dropdown edit-dropdown dropup">
          <div class="dropdown-thing" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <p > Edit </p>
            <i class="fa fa-pencil-square-o dropdown-toggle icon-edit-image"></i>
          </div>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to "Change photo",  edit_profile_user_image_path(@user), method: :get %></li>
              <li><%= link_to "Delete photo",  profile_user_image_path(@user, @photo), method: :delete %></li>
            </ul>
        </div>
      </div>
    </div>
</div>