config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/landing', to: 'pages#landing', as: :landing
  get '/about', to: 'pages#about', as: :about
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :communities, only: [:create]

  resources :profiles, only: [:show, :index, :edit, :update, :destroy] do
    resources :user_images, only: [:show, :destroy, :update, :edit]
    resources :matches, only: [:create]
    resources :dislikes, only: [:create]
    get '/onboard', to: 'profiles#onboard'
  end

  mount ActionCable.server => "/cable"
end

app/views/shared/_card.html.erb
<div class="card-container">
  <div class="card">
    <%= link_to profile_path(user), class: "card-link" do %>

      <div class="card-body">

        <!-- Slider main container -->
        <div class="swiper-container swiper-single-card">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <!-- test slide below -->
                <% images = user.user_images.order({id: :asc}) %>
                <div class="swiper-slide profile-photo" style="background-image: url(<%= image_path (images.first&.url || user.facebook_picture_url) %>);" ></div>
                <!-- end of test slide -->
                <% images.drop(1).each do |image| %>
                  <div class="swiper-slide profile-photo" style="background-image: url( <%= image_path image.url %>);" ></div>
                <% end %>
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination swiper-pagination-white swiper-single-card"></div>

            <!-- If we need navigation buttons -->
            <!-- <div class="swiper-button-prev swiper-single-card"></div> -->
            <!-- <div class="swiper-button-next swiper-single-card"></div> -->

            <!-- If we need scrollbar -->
            <div class="swiper-scrollbar swiper-single-card"></div>
        </div>

      </div>

      <div class="card-footer">
        <div class="card-footer-content text-left">
            <div><%= "#{user.first_name} #{user.age}" %></div>
            <div><%= user.course %></div>
        </div>
      </div>

  <% end %>
  </div>
</div>

app/views/shared/_edit-navbar.html.erb
<div class="navbar-meteor" style="background-color: <%= current_user&.community.brand_color || '#FFE270' %>;">
<!-- NAVBAR ON PROFILE SETTINGS -->
    <!-- Link to save LEFT icon -->
    <div class="navbar-meteor-left">
      <% if user_signed_in? %>
        <%= link_to profiles_path, class: "navbar-meteor-item navbar-meteor-link" do %>
          <i class="material-icons">keyboard_arrow_left</i>
        <% end %>
        <% else %>
        <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-meteor-item navbar-meteor-link" %>
      <% end %>
    </div>
    <!-- text CENTER -->
    <div id="edit-text-nav">
      <p>Edit your profile</p>
    </div>
    <!-- Link back RIGHT icon -->
    <div class="navbar-meteor-right">
      <% if user_signed_in? %>
      <%= link_to profiles_path, class: "navbar-meteor-item navbar-meteor-link" do  %>
        <i class="material-icons">done</i>
      <% end %>
      <% else %>
      <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-meteor-item navbar-meteor-link" %>
      <% end %>
    </div>
</div>

<%= content_for(:after_js) do %>
  <script>
  <% if current_user %>
    // get navbar barckground color in HEX
    var bgColor = "<%= "#{current_user&.community.brand_color[1..-1]}" || 'FFE270' %>";

    // change HEX to RGB
    function hexToRgb(hex) {
        var result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result ? {
            r: parseInt(result[1], 16),
            g: parseInt(result[2], 16),
            b: parseInt(result[3], 16)
        } : null;
    }

    // define if background color is light or not
    function colourIsLight(r, g, b) {
      var a = 1 - (0.299 * r + 0.587 * g + 0.114 * b) / 255;
      return (a < 0.5);
    }

    // select element (community name)
    var editProfileText = document.querySelector('#edit-text-nav');
    var editIcon1 = document.querySelector('.navbar-meteor-right a ');
    var editIcon2 = document.querySelector('.navbar-meteor-link');
    // set the text colour
    var textColour = colourIsLight(hexToRgb(bgColor).r, hexToRgb(bgColor).g, hexToRgb(bgColor).b) ? 'black' : 'white';

    // change color accordingly
    editProfileText.setAttribute('style', 'color: ' + textColour);
    editIcon1.setAttribute('style', 'color: ' + textColour);
    editIcon2.setAttribute('style', 'color: ' + textColour);

  <% end %>

  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_message.html.erb
<div class="message <%= user_is_messages_author ? "right" : "" %>">
  <%= link_to profile_path(message.user) do %>
    <%= image_tag message.user.facebook_picture_url, class: "avatar" %>
  <% end %>
  <div class="message-content">
    <p>
      <%= message.content %>
    </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-meteor <%= 'navbar-transparent' if params[:controller] == 'pages' %>" style="background-color: <%= current_user&.community&.brand_color || '' %>;">
  <!-- Dropdown list appearing on mobile only LEFT icon-->
  <% if user_signed_in? %>
  <div class="navbar-meteor-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="material-icons" data-toggle="dropdown">menu</i>
      <ul class="dropdown-menu dropdown-menu-left navbar-meteor-dropdown-menu">
        <li><%= link_to "Edit Profile", edit_profile_path(current_user.id) %> </li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
        <% end %></li>
      </ul>
    </div>
  </div>
  <!-- Dropdown list appearing on desktop only LEFT avatar-->
  <div class="navbar-meteor-item hidden-xs">
    <div class="dropdown">
     <div class="avatar dropdown-toggle" data-toggle="dropdown" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path current_user.user_images.first&.small_url || current_user.facebook_picture_url %>);"> </div>
      <ul class="dropdown-menu dropdown-menu-left navbar-meteor-dropdown-menu">
        <li><%= link_to "Edit profile", edit_profile_path(current_user.id) %> </li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
        <% end %></li>
      </ul>
    </div>
  </div>
  <% end %>

  <!-- Logo and name CENTER -->
  <%= link_to root_path, class: "navbar-brand" do %>
    <p><%= cl_image_tag "meteor-white_s1l4zo", height: 20 %> <%= current_user&.community&.title || "Meteor" %></p>
  <% end %>

  <!-- Links when logged in to messages desktop RIGHT text -->
  <div class="navbar-meteor-center hidden-xs">
    <% if user_signed_in? %>
      <%= link_to "messages", conversations_path, class: "navbar-meteor-item navbar-meteor-link" %>
    <% else %>
      <!-- Login link (when logged out) -->
      <% devise_mapping.omniauthable? %>
        <%- resource_class.omniauth_providers.each do |provider| %>
          <%= link_to "login", omniauth_authorize_path(resource_name, provider), class: "navbar-meteor-item navbar-meteor-link"%>
        <% end -%>
      <% end -%>
    </div>

  <!-- Links when logged in to messages mobile RIGHT icon -->
  <div class="navbar-meteor-right hidden-sm hidden-md hidden-lg">
    <% if user_signed_in? %>
      <%= link_to conversations_path, class: "navbar-meteor-item navbar-meteor-link" do %>
        <i class="material-icons">chat</i>
      <% end %>
    <% else %>
    <!-- Login link (when logged out) -->

      <% devise_mapping.omniauthable? %>
        <% resource_class.omniauth_providers.each do |provider| %>
          <%= link_to "login", omniauth_authorize_path(resource_name, provider), class: "navbar-meteor-item navbar-meteor-link"%>
        <% end %>
      <% end %>

  </div>

  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
  <% if current_user %>
    // get navbar barckground color in HEX
    var bgColor = "<%= "#{current_user&.community.brand_color[1..-1]}" || 'FFE270' %>";

    // change HEX to RGB
    function hexToRgb(hex) {
        var result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result ? {
            r: parseInt(result[1], 16),
            g: parseInt(result[2], 16),
            b: parseInt(result[3], 16)
        } : null;
    }

    // define if background color is light or not
    function colourIsLight(r, g, b) {
      var a = 1 - (0.299 * r + 0.587 * g + 0.114 * b) / 255;
      return (a < 0.5);
    }

    // select element (community name)
    var communityName = document.querySelector('.navbar-brand p');
    var messages = document.querySelector('.navbar-meteor-link');
    var icon1 = document.querySelector('.navbar-meteor-item i ');
    var icon2 = document.querySelector('.navbar-meteor-link i ');
    // set the text colour
    var textColour = colourIsLight(hexToRgb(bgColor).r, hexToRgb(bgColor).g, hexToRgb(bgColor).b) ? 'black' : 'white';

    // change color accordingly
    communityName.setAttribute('style', 'color: ' + textColour);
    messages.setAttribute('style', 'color: ' + textColour);
    icon1.setAttribute('style', 'color: ' + textColour);
    icon2.setAttribute('style', 'color: ' + textColour);
  <% end %>

  </script>
<% end %>